go=function(x,y,z,w)
{
m=c(x,y,z,w)
a=cal(m[1],m[2],m[3],m[4])
if(a=="N/A") a=cal(m[1],m[2],m[4],m[3])
if(a=="N/A") a=cal(m[1],m[3],m[2],m[4])
if(a=="N/A") a=cal(m[1],m[3],m[4],m[2])
if(a=="N/A") a=cal(m[1],m[4],m[2],m[3])
if(a=="N/A") a=cal(m[1],m[4],m[3],m[2])
if(a=="N/A") a=cal(m[2],m[1],m[3],m[4])
if(a=="N/A") a=cal(m[2],m[1],m[4],m[3])
if(a=="N/A") a=cal(m[2],m[3],m[1],m[4])
if(a=="N/A") a=cal(m[2],m[3],m[4],m[1])
if(a=="N/A") a=cal(m[2],m[4],m[1],m[3])
if(a=="N/A") a=cal(m[2],m[4],m[3],m[3])
if(a=="N/A") a=cal(m[3],m[1],m[2],m[4])
if(a=="N/A") a=cal(m[3],m[1],m[4],m[2])
if(a=="N/A") a=cal(m[3],m[2],m[1],m[4])
if(a=="N/A") a=cal(m[3],m[2],m[4],m[1])
if(a=="N/A") a=cal(m[3],m[4],m[1],m[2])
if(a=="N/A") a=cal(m[3],m[4],m[2],m[1])
if(a=="N/A") a=cal(m[4],m[1],m[2],m[3])
if(a=="N/A") a=cal(m[4],m[1],m[3],m[2])
if(a=="N/A") a=cal(m[4],m[2],m[1],m[3])
if(a=="N/A") a=cal(m[4],m[2],m[3],m[1])
if(a=="N/A") a=cal(m[4],m[3],m[1],m[2])
if(a=="N/A") a=cal(m[4],m[3],m[2],m[1])
 return(a)
 }